config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'contact', to:'static_pages#contact'
  get 'about', to:'static_pages#about'
  get 'about/moi', to: 'static_pages#moi', as:'petitnom'
  get 'prout', to: 'static_pages#mon_projet'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def moi
  end

  def mon_projet
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>
    <title>JeMePresente</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>
<p> @user</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<a href="<%= petitnom_path%>"> moi </a>

app/views/static_pages/moi.html.erb
<h1>StaticPages#moi</h1>
<p>Find me in app/views/static_pages/moi.html.erb</p>
....ET moi et moi et moi !

app/views/static_pages/mon_projet.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/mon_projet.html.erb</p>